version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=app
          - MYSQL_PASSWORD=root
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=himakuro_trekking_test
          - DB_HOST: 127.0.0.1
    steps:
      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-enable pdo_mysql
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
#      - restore_cache:
#          key: npm-v1-{{ checksum "package-lock.json" }}
#      - run:
#          name: npm ci
#          command: |
#            if [ ! -d node_modules ]; then
#              npm ci
#            fi
#      - save_cache:
#          key: npm-v1-{{ checksum "package-lock.json" }}
#          paths:
#            - node_modules
#      - run: npm run dev
      - run:
          name: DB_USERNAME
          command: echo $DB_USERNAME
      - run:
          name: DB_DATABASE
          command: echo $DB_DATABASE
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: test
          command: pwd
      - run: php artisan migrate
      - run:
          name: php test
          command: vendor/bin/phpunit
