version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      steps:
        - checkout
        - run: sudo apt update
        - run: sudo docker-php-ext-install zip pdo_mysql
        - run: sudo composer self-update
        - restore_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
        - run: composer install -n --prefer-dist
        - save_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
            paths:
              - vendor
        - run: npm ci
        - run: npm run dev
        - run:
            name: php test
            command: vendor/bin/phpunit
